pipeline:

  test:
    image: markharding/minds-front-base
    commands:
      - npm install && npm install -g typescript tslint gulp
      - npm test
      #- tslint -c tslint.json 'app/**/*.ts'

  build:
    image: markharding/minds-front-base
    commands:
      - npm install -g gulp
      - gulp build --aot --useCdn
    when:
      branch: [ 'master', 'test/codebuild' ]
  
  deploy:
    image: plugins/s3-sync:latest
    bucket: minds-repo
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: us-east-1
    source: public
    target: front/public
    delete: false
    when:
      branch: [ 'master', 'test/codebuild' ]
