pipeline:

  test:
    image: markharding/minds-front-base
    commands:
      - npm install && npm install -g typescript tslint gulp
      - npm test
      #- tslint -c tslint.json 'app/**/*.ts'

  build:
    image: markharding/minds-front-base
    commands:
      - npm install -g gulp
      - gulp build --aot --useCdn
      - gulp build --aot --shims
    when:
      event: [ push, tag, deployment ]
      branch: [ master, test/codebuild ]
  
  cp:
    image: plugins/s3-sync:latest
    bucket: minds-repo
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: us-east-1
    source: public
    target: front/public
    delete: false
    when:
      event: [ push, tag, deployment ]
      branch: [ master, test/codebuild ]

  deploy:
    image: minds/ecs-update:latest
    cluster: minds
    region: us-east-1
    service: app
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: [ push, tag, deployment ]
      branch: [ master, test/codebuild ]